sudo: required
services:
  - docker

before_install:
  - docker build -t diaconescu/hello-world -f Dockerfile.dev .

script:
  - docker run diaconescu/hello-world yarn test:unit

after_success:
  - docker build -t diaconescu/hello-world .

deploy:
  provider: script
  script: 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push diaconescu/hello-world
  on:
    branch: master
